@apiUrl = https://localhost:7558

@foodId = 0195725a-eb24-7f14-8b2f-d131671684f1
@woodId = 0195725b-5031-72cc-8969-16dd38932381
@goldId = 0195725b-b77e-7ed0-9387-9dca428f3337
@stoneId = 0195725b-ed2f-7842-8305-ceb37b249472

### Get liveness
GET {{apiUrl}}/alive
Accept: application/json

### Get health
GET {{apiUrl}}/health
Accept: application/json

### Get all resources
GET {{apiUrl}}/api/resources
Accept: application/json

### Update gold
PATCH {{apiUrl}}/api/resources/{{goldId}}/count/100
Accept: application/json
